### PR TITLE
return -2 when start or end is specified but not a number. fixes #24

### LINKED ISSUE #24: invalid start and end byte ranges should return -2
Expected:

```javascript
parse(200, 'bytes=x-100') === -2
```

Actual:

```javascript
parse(200, 'bytes=x-100') === [ { start: 0, end: 199 }, type: 'bytes' ]
```

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by mreinstein** [comment]
hate to be a pest but does have a shot at getting merged/published?  I think it should have minimal impact on stability.

**Comment by dougwilson** [comment]
yea, but just dealing with hurricane atm

**Comment by mreinstein** [comment]
Oh, didn't realize you were down there.  I hope you stay safe! 🙏

**Comment by dougwilson** [comment]
thx. I don't live there any more, but went down to help fam with prep and now clean up

**Comment by dougwilson** [comment]
As for this pr, it's a bug fix and looks fine and def something that should be merged 👍

**Comment by mreinstein** [comment]
Is there anything else I need to do on this one, or can it be merged/published as-is?

**Pull request closed without merging**
